### ISSUE TITLE
Identify largest trajectory

### ISSUE THREAD

**Issue by scpalbright** [blond-org/blond_common#34]
As discussed:

In some cases the well is cut in a way that the turning point is not seen, which prevents any potential well being identified in _find_potential_wells_cubic_.  An optional input to always return the largest available trajectory would be useful for this.

**Comment by alasheen** [comment]
Ok on my side, I'll propose an implementation soon

**Comment by alasheen** [comment]
Functionality was added in https://github.com/blond-org/blond_common/pull/37
See edge_is_max option in https://github.com/blond-org/blond_common/pull/37/commits/9fa0f7fc5752c8eaa85b6d051554dd4a3692159b
