### ISSUE TITLE
Datatype functionality enhancement

### ISSUE THREAD

**Issue by alasheen** [blond-org/blond_common#47]
- [x] Option to return a time based datatype using the reshape function with use_time

The present implementation should return a `timebase='interpolated'` datatype but returns `timebase=None` instead.

An option to return a `timebase==by_time` datatype would allow to reuse the time information when combining several datatypes (e.g. for `combine_single_sections` function).

- [x] Addition of datatypes with other types

E.g. to add a single float value to a time based datatype, or two time based datatypes

- [x] Adding interpolation to the data_type dict

E.g. for combination of functions, copy() function...

- [x] Extend single valued datatype when time base is passed

- [x] Check `try/except` loops in `combine_single_sections`

**Comment by scpalbright** [comment]
All done, included on upcoming pull request #48
